#!/bin/sh

if [ $button ]; then rofi -show menu -modi 'menu:rofi-power-menu' >/dev/null; fi

color=${color:='#81A1C1'}
background=${background:='#5e81ac'}
bar_color=${bar_color:='#2e3440'}
sep=${sep:=''}

echo "<span foreground='$background' background='$bar_color' size='x-large'>$sep</span> <span foreground='$color' rise='1'></span> "
