#!/bin/sh

if [ $button ];
then
    i3-msg exec "kitty --class 'peaclock' -e 'peaclock'" > /dev/null
fi

background=${background:='#5e81ac'}
bar_color=${bar_color:='#2e3440'}
sep=${sep:=''}
sep_fg=${sep_fg:='#3b4252'}
sep_bg=${sep_bg:='#8fbcbb'}
icon_color=${icon_color:='#81A1C1'}

echo "<span foreground='$sep_fg' background='$sep_bg'>$sep</span><span background='$background'> <span foreground='$icon_color'> </span> <span>$(date +"%H:%M:%S")</span> </span>"
